### ISSUE TITLE
Re-order sections on front page

### ISSUE THREAD

**Issue by AetherUnbound** [OrcaCollective/techbloc-directory#21]
Currently the order of sections is:
1. Get in touch
2. Community apps
3. Accountability
4. Bots
5. Friends of tech bloc

Ideally this would be rearranged so it becomes:
1. Accountability
2. Community apps
3. Bots
4. Get in touch
5. Friends of tech bloc

The latter ordering feels a bit more natural and showcases some of our biggest efforts at the top of the page.

**Comment by Myrfion** [comment]
Hi could I take this one?

**Comment by AetherUnbound** [comment]
Hi @Myrfion, please go ahead! I'll assign it to you 🙂

**Comment by Myrfion** [comment]
@AetherUnbound could u please check my PR? Thanks

**Comment by Myrfion** [comment]
Just wanna make it count toward the hacktobefest and the deadline is tonight

**Comment by AetherUnbound** [comment]
@Myrfion gave you some feedback on the PR 🙂

**Comment by Myrfion** [comment]
@AetherUnbound Thank you for getting back to me, I made an update

**Comment by DHRUVKHANDELWAL00** [comment]
hey @AetherUnbound ,can i work on it if it still need changes?

**Comment by AetherUnbound** [comment]
Oh sorry, this was addressed in #22!
